#!/usr/bin/env bash

set -e

export FPM_USER_ID=${FPM_USER_ID:-$(id -u)}
export FPM_GROUP_ID=${FPM_GROUP_ID:-$(id -g)}
export PHP_VERSION=${PHP_VERSION:-7.4}

CMD=$1

if [ "$CMD" == "" ]; then
    CMD="up -d"
fi

#if [ "$CMD" == "build" ]; then
#    exit 0
#fi

if [ "$ADMINUI_WEB_PORT" == "" ]; then
  export ADMINUI_WEB_PORT=8029
fi

docker-compose -p jelix-adminui-tests $CMD
